<a href="https://colab.research.google.com/github/bradyevans/BAYES/blob/main/notebooks/regression_in_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regression Example in Keras
Predicting house prices in Boston, Massachusetts

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/the-deep-learners/deep-learning-illustrated/blob/master/notebooks/regression_in_keras.ipynb)

#### Load dependencies

In [184]:
import numpy as np
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, BatchNormalization
from sklearn.preprocessing import StandardScaler
from keras.callbacks import EarlyStopping


#### Load data

In [185]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [186]:
X_train.shape

(404, 13)

In [187]:
X_valid.shape

(102, 13)

In [188]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [189]:
y_train[0]

15.2

In [190]:
# Standardize the dataset
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)

#### Design neural network architecture

In [191]:
model = Sequential()

model.add(Dense(16, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(8, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.4))


model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [192]:
model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_49 (Dense)                     │ (None, 16)                  │             224 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_32               │ (None, 16)                  │              64 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_50 (Dense)                     │ (None, 8)                   │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_33               │ (None, 8)                   │              32 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_15 (Dropout)                 │ (None, 8)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_51 (Dense)                     │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 465 (1.82 KB)

 Trainable params: 417 (1.63 KB)

 Non-trainable params: 48 (192.00 B)

#### Configure Model

In [193]:
model.compile(loss='mean_absolute_error', optimizer='adam')

#### Train!

In [183]:
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

model.fit(X_train, y_train,
          batch_size=8, epochs=150, verbose=1,
          validation_data=(X_valid, y_valid),
          callbacks=[early_stop])

Epoch 1/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 22.3518 - val_loss: 22.5546
Epoch 2/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 21.7684 - val_loss: 22.3092
Epoch 3/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.3707 - val_loss: 21.9711
Epoch 4/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.0288 - val_loss: 21.5029
Epoch 5/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.3035 - val_loss: 20.7624
Epoch 6/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.5372 - val_loss: 19.7187
Epoch 7/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.1121 - val_loss: 18.3675
Epoch 8/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.9265 - val_loss: 16.7746
Epoch 9/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.7704 - val_loss: 14.8935
Epoch 10/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.5325 - val_loss: 12.7017
Epoch 11/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.1996 - val_loss: 10.4831
Epoch 12/150
51/51 ━━━━━━━━━━━━━━━━━━━━ 

In [ ]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [ ]:
y_valid[42]

14.1

In [ ]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[20.880333]], dtype=float32)